### ISSUE TITLE
data.reduce undefined? 

### ISSUE THREAD

**Issue by maheshsundaram** [gildean/node-flowdock-stream#1]
I tried the example code in the README.MD with my organisation, flow and api key, but got this:

```
chronos@peppy:~/Projects/flowdock$ node app.js 
/home/chronos/Projects/flowdock/node_modules/flowdock-stream/index.js:58
        return callback(null, data.reduce(function nickReducer(obj, user) {
                                   ^
TypeError: undefined is not a function
    at JSONParseStream.getUserData (/home/chronos/Projects/flowdock/node_modules/flowdock-stream/index.js:58:36)
    at JSONParseStream.g (events.js:199:16)
    at JSONParseStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at JSONParseStream.Readable.push (_stream_readable.js:126:10)
    at JSONParseStream.Transform.push (_stream_transform.js:140:32)
    at JSONParseStream._flush (/home/chronos/Projects/flowdock/node_modules/flowdock-stream/jsonparser.js:43:14)
    at JSONParseStream.<anonymous> (_stream_transform.js:130:12)
    at JSONParseStream.g (events.js:199:16)
    at JSONParseStream.emit (events.js:104:17)
```

**Comment by gildean** [comment]
Hi, you probably tried to use a flow apikey, when in fact the module requires a personal apikey, as it uses the flowdock REST-API.
You can for example create another user for only the apikey, or use your own (note that it shows the name of the ower of the apikey as the sender when sending messages to the flow). Get the apikey from:
https://www.flowdock.com/account/tokens

I've also updated the module to pass the correct error from incorrect apikey etc.

**Comment by gildean** [comment]
I re-wrote parts of the code, the module can now support multiple flows nicely. If you could, please test the new example in the README now.

**Comment by gildean** [comment]
Can't reproduce this, so I'm assuming my previous though about the apikey was right.

**Comment by maheshsundaram** [comment]
Thank you!
